### ISSUE TITLE
Error message: Extension package twokings/hierarchical-routes has an invalid class (in Bolt 3.5.6)

### ISSUE THREAD

**Issue by laurens94** [xiaohutai/bolt-hierarchicalroutes#20] opened 2018-08-13 13:05 UTC
I have Bolt 3.5.6 installed. After installing the extension, I see the following error in the Bolt backend when opening config/menu.yml:

> Extension package twokings/hierarchical-routes has an invalid class 'Bolt\Extension\TwoKings\HierarchicalRoutes\HierarchicalRoutesExtension' and has been skipped.

**Comment by xiaohutai** [comment] 2018-08-21 11:40
I can't reproduce this. Got any more details?
How did you install the extension?

**Comment by laurens94** [comment] 2018-08-22 09:43
Using the /bolt/extensions route in the web-interface.
However it only occured once, after reloading the page the error was gone..

**Comment by xiaohutai** [comment] 2018-08-22 09:53
Oh right. That message comes from Bolt. Maybe it is a timing/caching issue.
That message is shown when the class could not be found/loaded at that time.

In bolt/bolt: https://github.com/bolt/bolt/blob/ab623edf7a3dc9a96d0a5090b0727ccfcfc0ba3a/src/Extension/Manager.php#L280

I'll close this issue for now as this could happen to every extension.
If it _is_ consistent, feel free to re-open or make a new issue 👍

**Closed as completed by xiaohutai** 2018-08-22 09:53 UTC
